name: Lint and Test

on:
  pull_request:
    branches:
      - master

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'

  install:
    needs: setup
    steps:
      - name: Install Dependencies
        run: npm ci

  lint:
    needs: [setup, install]
    steps:
      - name: Lint
        run: npm run lint

  test:
    needs: [setup, install, lint]
    steps:
      - name: Lint
        run: npm test
